{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 📘 Guía de Estudio: Regresión Lineal Múltiple con Ecuación Normal\n",
    "\n",
    "## ✅ Pasos para implementar una Regresión Lineal Múltiple\n",
    "\n",
    "### 1. Exploración inicial\n",
    "\n",
    "- Cargar el dataset desde un archivo CSV  \n",
    "- Examinar las primeras filas para entender la estructura  \n",
    "- Revisar estadísticas descriptivas de la variable objetivo  \n",
    "- Visualizar la distribución de la variable objetivo  \n",
    "- Identificar valores faltantes  \n",
    "\n",
    "\n",
    "### 2. Análisis de correlación\n",
    "\n",
    "- Seleccionar solo las columnas numéricas  \n",
    "- Calcular la matriz de correlación  \n",
    "- Identificar las características más correlacionadas con la variable objetivo  \n",
    "- Visualizar estas correlaciones con un mapa de calor  \n",
    "\n",
    "\n",
    "### 3. Selección de características\n",
    "\n",
    "- Elegir las características con mayor correlación con la variable objetivo  \n",
    "- Visualizar la relación entre cada característica seleccionada y la variable objetivo  \n",
    "\n",
    "\n",
    "### 4. Preparación de datos\n",
    "\n",
    "- Extraer la matriz de características (X) y la variable objetivo (y)  \n",
    "- Dividir en conjuntos de entrenamiento y validación (80%-20%)  \n",
    "- Estandarizar las características para que todas tengan la misma escala  \n",
    "\n",
    "\n",
    "### 5. Implementación de la regresión lineal\n",
    "\n",
    "- Añadir una columna de unos a la matriz X para el término de intercepto  \n",
    "- Aplicar la ecuación normal:  \n",
    "  ```\n",
    "  θ = (Xᵀ × X)^(-1) × Xᵀ × y\n",
    "  ```\n",
    "- Extraer el intercepto y los coeficientes  \n",
    "- Interpretar el significado de los coeficientes  \n",
    "\n",
    "\n",
    "### 6. Hacer predicciones\n",
    "\n",
    "- Multiplicar la matriz X por los coeficientes obtenidos  \n",
    "- Comparar las predicciones con los valores reales  \n",
    "\n",
    "\n",
    "### 7. Evaluar el modelo\n",
    "\n",
    "- Calcular métricas de error: **MSE**, **RMSE**, **MAE**, **MAPE**  \n",
    "- Calcular el coeficiente de determinación (**R²**)  \n",
    "- Interpretar cada métrica para entender el rendimiento  \n",
    "\n",
    "\n",
    "### 8. Visualizar resultados\n",
    "\n",
    "- Graficar valores reales vs. predicciones  \n",
    "- Analizar los residuos (errores) para detectar patrones  \n",
    "- Crear histogramas de residuos para verificar normalidad  \n",
    "\n",
    "\n",
    "### 9. Comparar con modelo más simple\n",
    "\n",
    "- Implementar un modelo usando solo la característica más importante  \n",
    "- Comparar el rendimiento (**R²**, **RMSE**) entre ambos modelos  \n",
    "- Cuantificar la mejora al usar múltiples características  \n",
    "\n",
    "\n",
    "## 🧪 Métodos Importantes en Python\n",
    "\n",
    "### 🔢 Funciones de NumPy\n",
    "\n",
    "- `np.array()`: Crea arrays de NumPy  \n",
    "- `np.c_[]`: Concatena arrays como columnas  \n",
    "- `np.ones()`: Crea un array de unos  \n",
    "- `np.linalg.inv()`: Calcula la inversa de una matriz  \n",
    "- `array.T`: Obtiene la transpuesta de un array  \n",
    "- `array.dot()`: Realiza multiplicación matricial  \n",
    "\n",
    "\n",
    "### 📊 Funciones de Pandas\n",
    "\n",
    "- `pd.read_csv()`: Lee datos desde un archivo CSV  \n",
    "- `dataframe.head()`: Muestra las primeras filas  \n",
    "- `dataframe.describe()`: Genera estadísticas descriptivas  \n",
    "- `dataframe.corr()`: Calcula la matriz de correlación  \n",
    "- `dataframe.select_dtypes()`: Filtra columnas por tipo de datos  \n",
    "\n",
    "\n",
    "### 📈 Funciones de Matplotlib y Seaborn\n",
    "\n",
    "- `plt.figure()`: Crea una nueva figura  \n",
    "- `plt.subplot()`: Crea subgráficos  \n",
    "- `plt.scatter()`: Crea gráficos de dispersión  \n",
    "- `plt.hist()`: Crea histogramas  \n",
    "- `sns.heatmap()`: Crea mapas de calor  \n",
    "\n",
    "\n",
    "### 🧠 Funciones de Scikit-learn\n",
    "\n",
    "- `train_test_split()`: Divide datos en conjuntos de entrenamiento y prueba  \n",
    "- `StandardScaler()`: Estandariza características  \n",
    "- `mean_squared_error()`: Calcula el MSE  \n",
    "\n",
    "\n",
    "## 📐 Métricas de Evaluación\n",
    "\n",
    "### Error Cuadrático Medio (MSE)\n",
    "\n",
    "- Promedio de los errores al cuadrado  \n",
    "- Penaliza más los errores grandes  \n",
    "- Unidades al cuadrado (difícil interpretación)  \n",
    "\n",
    "### Raíz del Error Cuadrático Medio (RMSE)\n",
    "\n",
    "- Raíz cuadrada del MSE  \n",
    "- Mismas unidades que la variable objetivo  \n",
    "- Más fácil de interpretar (error promedio)  \n",
    "\n",
    "### Error Absoluto Medio (MAE)\n",
    "\n",
    "- Promedio de los valores absolutos de los errores  \n",
    "- Menos sensible a valores atípicos que el MSE  \n",
    "\n",
    "### Error Porcentual Absoluto Medio (MAPE)\n",
    "\n",
    "- Error en términos de porcentaje  \n",
    "- Útil para entender la magnitud relativa del error  \n",
    "\n",
    "### Coeficiente de Determinación (R²)\n",
    "\n",
    "- Mide la proporción de varianza explicada por el modelo  \n",
    "- Varía entre 0 y 1 (más cercano a 1 es mejor)  \n",
    "- Interpretación:  \n",
    "  - Por debajo de 0.4: rendimiento **pobre**  \n",
    "  - Entre 0.4 y 0.6: rendimiento **moderado**  \n",
    "  - Entre 0.6 y 0.8: rendimiento **bueno**  \n",
    "  - Mayor a 0.8: rendimiento **excelente**  \n",
    "\n",
    "\n",
    "## ⚖️ Ventajas y Limitaciones de la Ecuación Normal\n",
    "\n",
    "### ✅ Ventajas\n",
    "\n",
    "- Solución directa (no iterativa)  \n",
    "- Garantiza encontrar el mínimo global  \n",
    "- No requiere hiperparámetros  \n",
    "- Determinista y fácil de implementar  \n",
    "\n",
    "### ⚠️ Limitaciones\n",
    "\n",
    "- Costosa para grandes conjuntos de datos  \n",
    "- Problemas con matrices mal condicionadas  \n",
    "- No funciona bien con multicolinealidad  \n",
    "- Inviable cuando hay más características que ejemplos  "
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
